name = "MusicXML"
uuid = "521615e9-e573-4eb2-bc7e-702d55c0bb95"
authors = ["Amin Yahyaabadi"]
version = "0.3.2"

[deps]
AcuteML = "6b84a0a3-a11a-41fa-a417-e600528de108"
TreeViews = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"

[compat]
AcuteML = "0.8.5, 0.9, 0.10"
TreeViews = "0.3"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
